eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

server:
  port: 9002

spring:
  application:
    name: restful
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9004
          jwk-set-uri: http://localhost:9004/oauth2/jwks

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG