eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${common.eureka.context-url}

server:
  port: ${common.restful.port}

spring:
  config:
    import: file:./common/src/main/resources/application-common.yml
  application:
    name: restful
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${common.auth.base-url}
          jwk-set-uri: ${common.auth.base-url}/oauth2/jwks

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG