#file: noinspection SpellCheckingInspection
server:
  port: 9001

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
  main:
    web-application-type: reactive

eureka:
  client:
    enabled: true
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka