eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

server:
  port: 9003

spring:
  application:
    name: collector
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG