eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${common.eureka.context-url}

server:
  port: ${common.collector.port}

spring:
  config:
    import: file:./common/src/main/resources/application-common.yml
  application:
    name: collector
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG